<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>AdvanceJavaProgramming</groupId>
  <artifactId>AdvanceJavaProgramming</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>
  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
       <plugin>
		    <groupId>com.coderplus.maven.plugins</groupId>
		    <artifactId>copy-rename-maven-plugin</artifactId>
		    <version>1.0</version>
		    <executions>
		        <execution>
		            <id>copy-file</id>
		            <phase>package</phase>
		            <goals>
		                <goal>copy</goal>
		            </goals>
		            <configuration>
		                <sourceFile>target/AdvanceJavaProgramming.war</sourceFile>
		                <destinationFile>C:/Users/abhishekd/OneDrive - Adobe/Abhishek/Adobe_Oct_21/Amity/Advanced Java/Jul 25 - Dec - 25/apache-tomcat-9.0.107-windows-x64/apache-tomcat-9.0.107/webapps/AdvanceJavaProgramming.war</destinationFile>
		            </configuration>
		        </execution>
		    </executions>
		</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.1</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>4.0.1</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  
</project>